### ISSUE TITLE
where is the model

### ISSUE THREAD

**Issue by zhyj3038** [chinakook/CTPN.mxnet#2]
hi, thanks very mush for your work of CTPN using mxnet.  
I want to use your model to validate the text detect result fast, can you share it ?

**Comment by chinakook** [comment]
The model's accuracy is not matched with the Tensorflow implementaion yet. I will tune it when I have time.

**Comment by chinakook** [comment]
I have tuned the CTPN model and now the accucracy get matched with the origin implementation.

**Comment by AndosonLiu** [comment]
Hello, 
I wanted to see the effect of CTPN, but I couldn't find the trained parameters in this reop, could you write how to get the trained  model into README file?
