### ISSUE TITLE
训练不收敛

### ISSUE THREAD

**Issue by lironghua318** [chinakook/CTPN.mxnet#6]
作者用的是什么数据集训练的？我用ICDAR2017_MLT模型不收敛，train_ctpn.py

**Comment by chinakook** [comment]
你需要制作数据集，把普通的bounding box变成宽度固定为16的小的bounding box的组合。

**Comment by lironghua318** [comment]
> 你需要制作数据集，把普通的bounding box变成宽度固定为16的小的bounding box的组合。
已经收敛了，非常感谢
