### ISSUE TITLE
运行demo出错

### ISSUE THREAD

**Issue by olojuwin** [chinakook/CTPN.mxnet#8]
RuntimeError: l_h2h_bias is not presented
请问你的模型是用的vggnet吗

**Comment by chinakook** [comment]
menu分支或dev分支应该是好的，resnet101吧，比vgg好

**Comment by olojuwin** [comment]
> menu分支或dev分支应该是好的，resnet101吧，比vgg好

谢谢你的回复，错误大概知道是什么原因了，resnet101太大了

**Comment by chinakook** [comment]
看起来像是LSTM哪里错了，master分支应该是有问题的

**Comment by olojuwin** [comment]
> 看起来像是LSTM哪里错了，master分支应该是有问题的

对的，已经解决了，请问你这个训练batch是在哪里设置的？

**Comment by chinakook** [comment]
Faster RCNN图像大小不一致，batch默认都是1

**Comment by olojuwin** [comment]
> Faster RCNN图像大小不一致，batch默认都是1

好的，谢谢 了，另外我在使用你的resnet的时候输入会报错。mxnet.base.MXNetError: Error in operator cls_prob: Expecting [1,22940] or [1,370,62]. But got [1,23940]

**Comment by chinakook** [comment]
这个就不清楚了，极有可能是数据的问题导致的
